exports.ALIAS = {
  status: '当前状态',
  symbol: '股票代码',
  name: '名称',
  avg_price: '当日平均价格',
  current: '当前价',
  high: '当日最高价',
  low: '当日最低价',
  percent: '涨跌幅',
  limit_up: '涨停',
  limit_down: '跌停',
  pb: '市净率',
  pe_lyr: '市盈率(静)',
  pe_ttm: '滚动市盈率',
  pe_forecast: '市盈率(动)',
  high52w: '52周最高',
  low52w: '52周最低',
  last_close: '昨收',
  open: '今开',
  turnover_rate: '换手率',
  volume: '成交量',
  time: '时间',
  pankou_scale: '委比',
  amplitude: '振幅',
  dividend: '股息率',
  float_market_capital: '流通市值',
  market_capital: '总市值',
  volume_scale: '量比',

  buy1: '买一',
  buy2: '买二',
  buy3: '买三',
  buy4: '买四',
  buy5: '买五',
  sell1: '卖一',
  sell2: '卖二',
  sell3: '卖三',
  sell4: '卖四',
  sell5: '卖五',

  margin_trading_buy_amt: '融资买入',
  margin_trading_net_buy_amt: '融资净买入',
  margin_trading_amt_balance: '两融余额',
  margin_trading_balance: '融资余额',
  short_selling_amt_balance: '融券余额',

  realtime_flow_amount: '今日实时资金流入/流出',

  price: '成交价',
  turn_valomn: '成交额',
  premium_rate: '溢价率',
  seller: '卖方',
  buyer: '买方',

  capital_large: '大单流入/流出',
  capital_medium: '中单流入/流出',
  capital_small: '小单流入/流出',
  capital_total: '总资金流入/流出',

  ncf_from_oa: '经营活动产生的现金流',
  ncf_from_ia: '投资活动产生的现金流',
  ncf_from_fa: '筹资活动产生的现金流',

  roe: '净资产收益率',
  np_per_share: '每股净资产',
  operate_cash_flow_ps: '每股现金流',
  capital_reserve: '每股资本公积金',
  undistri_profit_ps: '每股未分配利润',
  net_selling_rate: '净利率',

  assets: '总资产',
  liabilities: '总负债',
  asset_liab: '负债率',

  profit: '营业利润',
  income: '营业总收入',

  duty: '职位'
}
